#!/usr/bin/env zsh

# XDG directories
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

# Dotfiles overrides
export GOPATH="$HOME/.local/share/go"
export GNUPGHOME="$HOME/.local/share/gnupg"
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export PASSWORD_STORE_DIR="$HOME/.local/share/password-store"
export PYTHONUSERBASE="$HOME/.local/share/python"
export ZDOTDIR="$HOME/.config/zsh"
export npm_config_prefix="$HOME/.local/share/npm"

# Local programs and scripts
if ! printf "$PATH" | grep -q "$HOME/.local/bin"; then
	PATH="$PATH:$GOPATH/bin"
	PATH="$PATH:$PYTHONUSERBASE/bin"
	PATH="$PATH:$npm_config_prefix/bin"
	export PATH="$HOME/.local/bin:$PATH"
fi

# Default programs
export BROWSER=brave
export EDITOR=nvim
export TERMINAL=kitty

# Graphical session
export _JAVA_AWT_WM_NONREPARENTING=1
export CLIPBOARD=wl-copy
export VDPAU_DRIVER=radeonsi
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

# GTK and QT theming
export GTK_THEME=Adwaita-dark
export ICON_DIR=/usr/share/icons/breeze-dark
export QT_QPA_PLATFORMTHEME=qt5ct

# SSH agent
export SSH_AGENT_PID="$(pgrep -f ssh-agent)"
export SSH_AUTH_SOCK="$HOME/.cache/ssh-agent.socket"

# Misc settings
export BAT_THEME="base16"
export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Various aliases
alias f=vifm
alias e=nvim
alias ls='ls --color=auto'
alias q=exit
alias vim=nvim
