#!/usr/bin/env zsh

# Local programs and scripts
export PATH="$HOME/.local/bin:$PATH"

# Global Tex Live installation
export PATH="$PATH:/usr/local/texlive/2020/bin/x86_64-linux/"

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Dotfiles overrides
export ADOTDIR="$HOME/.local/share/zsh"
export ZDOTDIR="$HOME/.config/zsh"
export LESSHISTFILE="-"

# Default programs
export EDITOR=nvim
export TERMINAL=alacritty
export BROWSER=firefox

# SSH agent
export SSH_AGENT_PID=$(pgrep -f ssh-agent)
export SSH_AUTH_SOCK="$HOME/.cache/ssh-agent.socket"

# Coloured less output
export LESS_TERMCAP_mb=$'\e[1;36m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;35m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;37m'

# Various aliases
[[ "$OSTYPE" == 'linux-gnu' ]] && alias ls='ls --color=auto' || alias ls='ls -G'
alias vim=nvim
