#!/usr/bin/env zsh

# Silently start some programs in the background
(! pgrep -f mpd && mpd) &> /dev/null
(! pgrep -f ssh-agent && eval $(ssh-agent)) &> /dev/null
(! pgrep -f syncthing && syncthing --no-browser &) &> /dev/null

# Present a session picker and power menu
while true; do
	print '\nChoose an option:\n\n' \
		'1) Start X11\n' \
		'2) Start tmux\n\n' \
		'3) Logout\n' \
		'4) Suspend\n' \
		'5) Reboot\n' \
		'6) Shutdown\n'

	read NUM\?'(number) '
	case $NUM in
		1) startx &> /dev/null ;;
		2) tmux ;;
		3) exit ;;
		4) qsuspend ;;
		5) qreboot ;;
		6) qpoweroff ;;
	esac
done
