#!/bin/sh

# Monitor settings
[ -f $HOME/.config/bspwm/monitors ] && . $HOME/.config/bspwm/monitors

# Make using the mouse less annoying
bspc config focus_follows_pointer true

# Borders are always black
bspc config normal_border_color  '#0d0d0d'
bspc config active_border_color  '#0d0d0d'
bspc config focused_border_color '#0d0d0d'

# Leave some breathing room
bspc config border_width 2
bspc config window_gap   24

# Simple splitting
bspc config split_ratio     0.5
bspc config presel_feedback false
