#!/bin/sh

# Configure each monitor
for MON in $(xrandr --query | grep ' connected' | awk '{print $1}' | tr -s '\n' ' '); do
	bspc monitor "$MON" -d 1 2 3 4 5 6 7 8 9 0
done

# Make using the mouse less annoying
bspc config focus_follows_pointer true

# Subtle border colours
bspc config normal_border_color  '#0d0d0d'
bspc config active_border_color  '#333333'
bspc config focused_border_color '#595959'

# Leave some breathing room
bspc config border_width 1
bspc config window_gap   1

# Borderless and gapless monocle
bspc config borderless_monocle true
bspc config gapless_monocle    true

# Simple splitting
bspc config split_ratio     0.5
bspc config presel_feedback false

# Float all windows by default
bspc rule -a \* state=floating
