#!/bin/sh

if ! test -d /sys/class/power_supply/BAT*; then
	exit 0
fi

CAP=$(cat /sys/class/power_supply/BAT*/capacity)

if [ "$CAP" -le 20 ]; then
	ICON='❗'
else
	case $(cat /sys/class/power_supply/BAT*/status) in
		'Charging')    ICON='🔌' ;;
		'Discharging') ICON='🔋' ;;
		'Full')        ICON='⚡' ;;
		*)             ICON='❔' ;;
	esac
fi

printf "$ICON Bat $CAP%%"
