#!/bin/sh

BATS="$(echo /sys/class/power_supply/BAT*)"

if [ "$BATS" = '/sys/class/power_supply/BAT*' ]; then
	exit 0
fi

for BAT in $BATS; do
	CAP="$(cat $BAT/capacity)"

	if [ "$CAP" -le 20 ]; then
		ICON='❗'
	else
		case "$(cat $BAT/status)" in
			'Charging')    ICON='🔌' ;;
			'Discharging') ICON='🔋' ;;
			'Full')        ICON='⚡' ;;
			*)             ICON='❔' ;;
		esac
	fi

	printf "$ICON Bat $CAP%%"
	exit 0
done
