#!/bin/sh

ETHS="$(echo /sys/class/net/e*)"

if [ "$ETHS" = '/sys/class/net/e*' ]; then
	exit 0
fi

for ETH in $ETHS; do
	if grep -q 'up' "$(printf $ETH/operstate)"; then
		printf '🌐 Eth ON'
		exit 0
	fi
done

printf '❎ Eth OFF'
