#!/bin/sh

WLNS="$(echo /sys/class/net/w*)"

if [ "$WLNS" = '/sys/class/net/w*' ]; then
	exit 0
fi

for WLN in $WLNS; do
	if grep -q 'up' "$(printf $WLN/operstate)"; then
		printf "📶 Wln $(awk '/^\s*w/ {print int($3)}' /proc/net/wireless)%%"
		exit 0
	fi
done

printf '❎ Wln OFF'
