#!/bin/sh

# Local programs and scripts
export XDG_DATA_DIRS="$HOME/.local/share/applications:$XDG_DATA_DIRS"

# Various local settings
[ -f $HOME/.xprofile ] && . $HOME/.xprofile

# GTK and QT theming
export GTK2_RC_FILES="$HOME/.config/gtk-2.0/gtkrc-2.0"
export QT_QPA_PLATFORMTHEME=qt5ct
xsettingsd &
xrdb << EOF
Xcursor.theme: Adwaita
Xcursor.size: 16
EOF
xsetroot -cursor_name left_ptr

# Session bus
export $(dbus-launch)

# Window manager
exec i3
